<?php

function getCountries($userLang): string {

    // get countries names from strings file
    require($_SERVER['DOCUMENT_ROOT'] . '/localization/strings.php');
    $lang = getLang($userLang);

    return trim('[
    {"code":"default", "country_code":"", "flag":"", "name":"' . $lang['def'] . '"},
    {"code":"af", "country_code":"+93", "flag":"🇦🇫", "name":"'. $lang['Afghanistan'] .'"},
    {"code":"al", "country_code":"+355", "flag":"🇦🇱", "name":"'. $lang['Albania'] .'"},
    {"code":"dz", "country_code":"+213", "flag":"🇩🇿", "name":"' . $lang['Algeria'] . '"},
    {"code":"dz", "country_code":"+1684", "flag":"🇦🇸", "name":"'. $lang['American_Samoa'] .'"},
    {"code":"ad", "country_code":"+376", "flag":"🇦🇩", "name":"'. $lang['Andorra'] .'"},
    {"code":"ao", "country_code":"+244", "flag":"🇦🇴", "name":"'. $lang['Angola'] .'"},
    {"code":"ag", "calling_code":"+1268", "flag":"🇦🇬", "name":"'. $lang['Antigua_Barbuda'] .'"},
    {"code":"ar", "calling_code":"+54", "flag":"🇦🇷", "name":"'. $lang['Argentina'] .'"},
    {"code":"am", "calling_code":"+374", "flag":"🇦🇲", "name":"'. $lang['Armenia'] .'"},
    {"code":"au", "calling_code":"+61", "flag":"🇦🇺", "name":"'. $lang['Australia'] .'"},
    {"code":"at", "calling_code":"+43", "flag":"🇦🇹", "name":"'. $lang['Austria'] .'"},
    {"code":"az", "calling_code":"+994", "flag":"🇦🇿", "name":"'. $lang['Azerbaijan'] .'"},
    {"code":"bs", "calling_code":"+1242", "flag":"🇧🇸", "name":"'. $lang['Bahamas'] .'"},
    {"code":"bh", "calling_code":"+973", "flag":"🇧🇭", "name":"' . $lang['Bahrain'] . '"},
    {"code":"bd", "calling_code":"+880", "flag":"🇧🇩", "name":"'. $lang['Bangladesh'] .'"},
    {"code":"bb", "calling_code":"+1246", "flag":"🇧🇧", "name":"'. $lang['Barbados'] .'"},
    {"code":"by", "calling_code":"+375", "flag":"🇧🇾", "name":"'. $lang['Belarus'] .'"},
    {"code":"be", "calling_code":"+32", "flag":"🇧🇪", "name":"'. $lang['Belgium'] .'"},
    {"code":"bz", "calling_code":"+501", "flag":"🇧🇿", "name":"'. $lang['Belize'] .'"},
    {"code":"bj", "calling_code":"+229", "flag":"🇧🇯", "name":"'. $lang['Benin'] .'"},
    {"code":"bt", "calling_code":"+975", "flag":"🇧🇹", "name":"'. $lang['Bhutan'] .'"},
    {"code":"bo", "calling_code":"+591", "flag":"🇧🇴", "name":"'. $lang['Bolivia'] .'"},
    {"code":"ba", "calling_code":"+387", "flag":"🇧🇦", "name":"'. $lang['Bosnia_Herzegovina'] .'"},
    {"code":"bw", "calling_code":"+267", "flag":"🇧🇼", "name":"'. $lang['Botswana'] .'"},
    {"code":"br", "calling_code":"+55", "flag":"🇧🇷", "name":"'. $lang['Brazil'] .'"},
    {"code":"bn", "calling_code":"+673", "flag":"🇧🇳", "name":"'. $lang['Brunei_Darussalam'] .'"},
    {"code":"bg", "calling_code":"+359", "flag":"🇧🇬", "name":"'. $lang['Bulgaria'] .'"},
    {"code":"bf", "calling_code":"+226", "flag":"🇧🇫", "name":"'. $lang['BurkinaFaso'] .'"},
    {"code":"bi", "calling_code":"+257", "flag":"🇧🇮", "name":"'. $lang['Burundi'] .'"},
    {"code":"cv", "calling_code":"+238", "flag":"🇨🇻", "name":"'. $lang['CapeVerde'] .'"},
    {"code":"kh", "calling_code":"+855", "flag":"🇰🇭", "name":"'. $lang['Cambodia'] .'"},
    {"code":"cm", "calling_code":"+237", "flag":"🇨🇲", "name":"'. $lang['Cameroon'] .'"},
    {"code":"ca", "calling_code":"+1", "flag":"🇨🇦", "name":"'. $lang['Canada'] .'"},
    {"code":"cf", "calling_code":"+236", "flag":"🇨🇫", "name":"'. $lang['CentralAfrican'] .'"},
    {"code":"td", "calling_code":"+235", "flag":"🇹🇩", "name":"'. $lang['Chad'] .'"},
    {"code":"cl", "calling_code":"+56", "flag":"🇨🇱", "name":"'. $lang['Chile'] .'"},
    {"code":"cn", "calling_code":"+86", "flag":"🇨🇳", "name":"'. $lang['China'] .'"},
    {"code":"co", "calling_code":"+57", "flag":"🇨🇴", "name":"'. $lang['Colombia'] .'"},
    {"code":"km", "calling_code":"+269", "flag":"🇰🇲", "name":"' . $lang['Comoros'] . '"},
    {"code":"cg", "calling_code":"+242", "flag":"🇨🇬", "name":"'. $lang['RepublicOfCongo'] .'"},
    {"code":"cd", "calling_code":"+243", "flag":"🇨🇩", "name":"'. $lang['CongoDemocratic'] .'"},
    {"code":"cr", "calling_code":"+506", "flag":"🇨🇷", "name":"'. $lang['CostaRica'] .'"},
    {"code":"ci", "calling_code":"+225", "flag":"🇨🇮", "name":"'. $lang['CotedIvoire'] .'"},
    {"code":"hr", "calling_code":"+385", "flag":"🇭🇷", "name":"'. $lang['Croatia'] .'"},
    {"code":"cu", "calling_code":"+53", "flag":"🇨🇺", "name":"'. $lang['Cuba'] .'"},
    {"code":"cy", "calling_code":"+357", "flag":"🇨🇾", "name":"'. $lang['Cyprus'] .'"},
    {"code":"cz", "calling_code":"+420", "flag":"🇨🇿", "name":"'. $lang['Czechia'] .'"},
    {"code":"dk", "calling_code":"+45", "flag":"🇩🇰", "name":"'. $lang['Denmark'] .'"},
    {"code":"dj", "calling_code":"+253", "flag":"🇩🇯", "name":"' . $lang['Djibouti'] . '"},
    {"code":"dm", "calling_code":"+1767", "flag":"🇩🇲", "name":"'. $lang['Dominica'] .'"},
    {"code":"do", "calling_code":"+1809", "flag":"🇩🇴", "name":"'. $lang['DominicanRepublic'] .'"},
    {"code":"ec", "calling_code":"+593", "flag":"🇪🇨", "name":"'. $lang['Ecuador'] .'"},
    {"code":"eg", "calling_code":"+20", "flag":"🇪🇬", "name":"' . $lang['Egypt'] . '"},
    {"code":"sv", "calling_code":"+503", "flag":"🇸🇻", "name":"'. $lang['ElSalvador'] .'"},
    {"code":"gq", "calling_code":"+240", "flag":"🇬🇶", "name":"'. $lang['EquatorialGuinea'] .'"},
    {"code":"er", "calling_code":"+291", "flag":"🇪🇷", "name":"'. $lang['Eritrea'] .'"},
    {"code":"ee", "calling_code":"+372", "flag":"🇪🇪", "name":"'. $lang['Estonia'] .'"},
    {"code":"sz", "calling_code":"+268", "flag":"🇸🇿", "name":"'. $lang['Eswatini'] .'"},
    {"code":"et", "calling_code":"+251", "flag":"🇪🇹", "name":"'. $lang['Ethiopia'] .'"},
    {"code":"fj", "calling_code":"+679", "flag":"🇫🇯", "name":"'. $lang['Fiji'] .'"},
    {"code":"fi", "calling_code":"+358", "flag":"🇫🇮", "name":"'. $lang['Finland'] .'"},
    {"code":"fr", "calling_code":"+33", "flag":"🇫🇷", "name":"'. $lang['France'] .'"},
    {"code":"ga", "calling_code":"+241", "flag":"🇬🇦", "name":"'. $lang['Gabon'] .'"},
    {"code":"gm", "calling_code":"+220", "flag":"🇬🇲", "name":"'. $lang['Gambia'] .'"},
    {"code":"ge", "calling_code":"+995", "flag":"🇬🇪", "name":"'. $lang['Georgia'] .'"},
    {"code":"de", "calling_code":"+49", "flag":"🇩🇪", "name":"'. $lang['Germany'] .'"},
    {"code":"gh", "calling_code":"+233", "flag":"🇬🇭", "name":"'. $lang['Ghana'] .'"},
    {"code":"gr", "calling_code":"+30", "flag":"🇬🇷", "name":"'. $lang['Greece'] .'"},
    {"code":"gr", "calling_code":"+299", "flag":"🇬🇱", "name":"'. $lang['Greenland'] .'"},
    {"code":"gd", "calling_code":"+1473", "flag":"🇬🇩", "name":"'. $lang['Grenada'] .'"},
    {"code":"gt", "calling_code":"+502", "flag":"🇬🇹", "name":"'. $lang['Guatemala'] .'"},
    {"code":"gn", "calling_code":"+224", "flag":"🇬🇳", "name":"'. $lang['Guinea'] .'"},
    {"code":"gw", "calling_code":"+245", "flag":"🇬🇼", "name":"'. $lang['GuineaBissau'] .'"},
    {"code":"gy", "calling_code":"+592", "flag":"🇬🇾", "name":"'. $lang['Guyana'] .'"},
    {"code":"ht", "calling_code":"+509", "flag":"🇭🇹", "name":"'. $lang['Haiti'] .'"},
    {"code":"hn", "calling_code":"+504", "flag":"🇭🇳", "name":"'. $lang['Honduras'] .'"},
    {"code":"hu", "calling_code":"+36", "flag":"🇭🇺", "name":"'. $lang['Hungary'] .'"},
    {"code":"is", "calling_code":"+354", "flag":"🇮🇸", "name":"'. $lang['Iceland'] .'"},
    {"code":"in", "calling_code":"+91", "flag":"🇮🇳", "name":"'. $lang['India'] .'"},
    {"code":"id", "calling_code":"+62", "flag":"🇮🇩", "name":"'. $lang['Indonesia'] .'"},
    {"code":"iq", "calling_code":"+964", "flag":"🇮🇶", "name":"' . $lang['Iraq'] . '"},
    {"code":"ir", "calling_code":"+98", "flag":"🇮🇷", "name":"'. $lang['Iran'] .'"},
    {"code":"ie", "calling_code":"+353", "flag":"🇮🇪", "name":"'. $lang['Ireland'] .'"},
    {"code":"it", "calling_code":"+39", "flag":"🇮🇹", "name":"'. $lang['Italy'] .'"},
    {"code":"jm", "calling_code":"+1658", "flag":"🇯🇲", "name":"'. $lang['Jamaica'] .'"},
    {"code":"jp", "calling_code":"+81", "flag":"🇯🇵", "name":"'. $lang['Japan'] .'"},
    {"code":"jo", "calling_code":"+962", "flag":"🇯🇴", "name":"' . $lang['Jordan'] . '"},
    {"code":"kz", "calling_code":"+997", "flag":"🇰🇿", "name":"'. $lang['Kazakhstan'] .'"},
    {"code":"ke", "calling_code":"+254", "flag":"🇰🇪", "name":"'. $lang['Kenya'] .'"},
    {"code":"ki", "calling_code":"+686", "flag":"🇰🇮", "name":"'. $lang['Kiribati'] .'"},
    {"code":"kp", "calling_code":"+850", "flag":"🇰🇵", "name":"'. $lang['NorthKorea'] .'"},
    {"code":"kr", "calling_code":"+82", "flag":"🇰🇷", "name":"'. $lang['SouthKorea'] .'"},
    {"code":"kw", "calling_code":"+383", "flag":"🇽🇰", "name":"' . $lang['Kosovo'] . '"},
    {"code":"kw", "calling_code":"+965", "flag":"🇰🇼", "name":"' . $lang['Kuwait'] . '"},
    {"code":"kg", "calling_code":"+996", "flag":"🇰🇬", "name":"'. $lang['Kyrgyzstan'] .'"},
    {"code":"la", "calling_code":"+856", "flag":"🇱🇦", "name":"'. $lang['Lao'] .'"},
    {"code":"lv", "calling_code":"+371", "flag":"🇱🇻", "name":"'. $lang['Latvia'] .'"},
    {"code":"lb", "calling_code":"+961", "flag":"🇱🇧", "name":"' . $lang['Lebanon'] . '"},
    {"code":"ls", "calling_code":"+266", "flag":"🇱🇸", "name":"'. $lang['Lesotho'] .'"},
    {"code":"lr", "calling_code":"+231", "flag":"🇱🇷", "name":"'. $lang['Liberia'] .'"},
    {"code":"ly", "calling_code":"+218", "flag":"🇱🇾", "name":"' . $lang['Libya'] . '"},
    {"code":"li", "calling_code":"+423", "flag":"🇱🇮", "name":"'. $lang['Liechtenstein'] .'"},
    {"code":"lt", "calling_code":"+370", "flag":"🇱🇹", "name":"'. $lang['Lithuania'] .'"},
    {"code":"lu", "calling_code":"+352", "flag":"🇱🇺", "name":"'. $lang['Luxembourg'] .'"},
    {"code":"mg", "calling_code":"+261", "flag":"🇲🇬", "name":"'. $lang['Madagascar'] .'"},
    {"code":"mw", "calling_code":"+265", "flag":"🇲🇼", "name":"'. $lang['Malawi'] .'"},
    {"code":"my", "calling_code":"+60", "flag":"🇲🇾", "name":"'. $lang['Malaysia'] .'"},
    {"code":"mv", "calling_code":"+960", "flag":"🇲🇻", "name":"'. $lang['Maldives'] .'"},
    {"code":"ml", "calling_code":"+223", "flag":"🇲🇱", "name":"'. $lang['Mali'] .'"},
    {"code":"mt", "calling_code":"+356", "flag":"🇲🇹", "name":"'. $lang['Malta'] .'"},
    {"code":"mh", "calling_code":"+692", "flag":"🇲🇭", "name":"'. $lang['MarshallIslands'] .'"},
    {"code":"ma", "calling_code":"+222", "flag":"🇲🇷", "name":"' . $lang['Mauritania'] . '"},
    {"code":"mu", "calling_code":"+230", "flag":"🇲🇺", "name":"'. $lang['Mauritius'] .'"},
    {"code":"mx", "calling_code":"+52", "flag":"🇲🇽", "name":"'. $lang['Mexico'] .'"},
    {"code":"fm", "calling_code":"+691", "flag":"🇫🇲", "name":"'. $lang['Micronesia'] .'"},
    {"code":"md", "calling_code":"+373", "flag":"🇲🇩", "name":"'. $lang['Moldova'] .'"},
    {"code":"mc", "calling_code":"+377", "flag":"🇲🇨", "name":"'. $lang['Monaco'] .'"},
    {"code":"mn", "calling_code":"+976", "flag":"🇲🇳", "name":"'. $lang['Mongolia'] .'"},
    {"code":"me", "calling_code":"+382", "flag":"🇲🇪", "name":"'. $lang['Montenegro'] .'"},
    {"code":"ma", "calling_code":"+212", "flag":"🇲🇦", "name":"' . $lang['Morocco'] . '"},
    {"code":"mz", "calling_code":"+258", "flag":"🇲🇿", "name":"'. $lang['Mozambique'] .'"},
    {"code":"mm", "calling_code":"+95", "flag":"🇲🇲", "name":"'. $lang['Myanmar'] .'"},
    {"code":"na", "calling_code":"+264", "flag":"🇳🇦", "name":"'. $lang['Namibia'] .'"},
    {"code":"nr", "calling_code":"+674", "flag":"🇳🇷", "name":"'. $lang['Nauru'] .'"},
    {"code":"np", "calling_code":"+977", "flag":"🇳🇵", "name":"'. $lang['Nepal'] .'"},
    {"code":"nl", "calling_code":"+31", "flag":"🇳🇱", "name":"'. $lang['Netherlands'] .'"},
    {"code":"nz", "calling_code":"+64", "flag":"🇳🇿", "name":"'. $lang['NewZealand'] .'"},
    {"code":"ni", "calling_code":"+505", "flag":"🇳🇮", "name":"'. $lang['Nicaragua'] .'"},
    {"code":"ne", "calling_code":"+227", "flag":"🇳🇪", "name":"'. $lang['Niger'] .'"},
    {"code":"ng", "calling_code":"+234", "flag":"🇳🇬", "name":"'. $lang['Nigeria'] .'"},
    {"code":"mk", "calling_code":"+389", "flag":"🇲🇰", "name":"'. $lang['NorthMacedonia'] .'"},
    {"code":"no", "calling_code":"+47", "flag":"🇳🇴", "name":"'. $lang['Norway'] .'"},
    {"code":"om", "calling_code":"+968", "flag":"🇴🇲", "name":"' . $lang['Oman'] . '"},
    {"code":"pk", "calling_code":"+92", "flag":"🇵🇰", "name":"'. $lang['Pakistan'] .'"},
    {"code":"pw", "calling_code":"+680", "flag":"🇵🇼", "name":"'. $lang['Palau'] .'"},
    {"code":"pa", "calling_code":"+970", "flag":"🇵🇸", "name":"' . $lang['Palestine'] . '"},
    {"code":"pa", "calling_code":"+507", "flag":"🇵🇦", "name":"'. $lang['Panama'] .'"},
    {"code":"pg", "calling_code":"+675", "flag":"🇵🇬", "name":"'. $lang['PapuaNewGuinea'] .'"},
    {"code":"py", "calling_code":"+595", "flag":"🇵🇾", "name":"'. $lang['Paraguay'] .'"},
    {"code":"pe", "calling_code":"+51", "flag":"🇵🇪", "name":"'. $lang['Peru'] .'"},
    {"code":"ph", "calling_code":"+63", "flag":"🇵🇭", "name":"'. $lang['Philippines'] .'"},
    {"code":"pl", "calling_code":"+48", "flag":"🇵🇱", "name":"'. $lang['Poland'] .'"},
    {"code":"pt", "calling_code":"+351", "flag":"🇵🇹", "name":"'. $lang['Portugal'] .'"},
    {"code":"qa", "calling_code":"+974", "flag":"🇶🇦", "name":"' . $lang['Qatar'] . '"},
    {"code":"ro", "calling_code":"+40", "flag":"🇷🇴", "name":"'. $lang['Romania'] .'"},
    {"code":"ru", "calling_code":"+7", "flag":"🇷🇺", "name":"'. $lang['Russia'] .'"},
    {"code":"rw", "calling_code":"+250", "flag":"🇷🇼", "name":"'. $lang['Rwanda'] .'"},
    {"code":"kn", "calling_code":"+1869", "flag":"🇰🇳", "name":"'. $lang['SaintKitts'] .'"},
    {"code":"lc", "calling_code":"+1758", "flag":"🇱🇨", "name":"'. $lang['SaintLucia'] .'"},
    {"code":"vc", "calling_code":"+1784", "flag":"🇻🇨", "name":"'. $lang['SaintVincent'] .'"},
    {"code":"ws", "calling_code":"+685", "flag":"🇼🇸", "name":"'. $lang['Samoa'] .'"},
    {"code":"sm", "calling_code":"+378", "flag":"🇸🇲", "name":"'. $lang['SanMarino'] .'"},
    {"code":"st", "calling_code":"+239", "flag":"🇸🇹", "name":"'. $lang['SaoTomePríncipe'] .'"},
    {"code":"sa", "calling_code":"+966", "flag":"🇸🇦", "name":"' . $lang['Saudi_Arabia'] . '"},
    {"code":"sn", "calling_code":"+221", "flag":"🇸🇳", "name":"'. $lang['Senegal'] .'"},
    {"code":"rs", "calling_code":"+381", "flag":"🇷🇸", "name":"'. $lang['Serbia'] .'"},
    {"code":"sc", "calling_code":"+248", "flag":"🇸🇨", "name":"'. $lang['Seychelles'] .'"},
    {"code":"sl", "calling_code":"+232", "flag":"🇸🇱", "name":"'. $lang['SierraLeone'] .'"},
    {"code":"sg", "calling_code":"+65", "flag":"🇸🇬", "name":"'. $lang['Singapore'] .'"},
    {"code":"sk", "calling_code":"+421", "flag":"🇸🇰", "name":"'. $lang['Slovakia'] .'"},
    {"code":"si", "calling_code":"+386", "flag":"🇸🇮", "name":"'. $lang['Slovenia'] .'"},
    {"code":"sb", "calling_code":"+677", "flag":"🇸🇧", "name":"'. $lang['SolomonIslands'] .'"},
    {"code":"so", "calling_code":"+252", "flag":"🇸🇴", "name":"' . $lang['Somalia'] . '"},
    {"code":"za", "calling_code":"+27", "flag":"🇿🇦", "name":"'. $lang['SouthAfrica'] .'"},
    {"code":"ss", "calling_code":"+211", "flag":"🇸🇸", "name":"'. $lang['SouthSudan'] .'"},
    {"code":"es", "calling_code":"+34", "flag":"🇪🇸", "name":"'. $lang['Spain'] .'"},
    {"code":"lk", "calling_code":"+94", "flag":"🇱🇰", "name":"'. $lang['SriLanka'] .'"},
    {"code":"sd", "calling_code":"+249", "flag":"🇸🇩", "name":"' . $lang['Sudan'] . '"},
    {"code":"sr", "calling_code":"+597", "flag":"🇸🇷", "name":"'. $lang['Suriname'] .'"},
    {"code":"se", "calling_code":"+46", "flag":"🇸🇪", "name":"'. $lang['Sweden'] .'"},
    {"code":"ch", "calling_code":"+41", "flag":"🇨🇭", "name":"'. $lang['Switzerland'] .'"},
    {"code":"sy", "calling_code":"+963", "flag":"🇸🇾", "name":"' . $lang['Syria'] . '"},
    {"code":"tj", "calling_code":"+886", "flag":"🇹🇼", "name":"'. $lang['Taiwan'] .'"},
    {"code":"tj", "calling_code":"+992", "flag":"🇹🇯", "name":"'. $lang['Tajikistan'] .'"},
    {"code":"tz", "calling_code":"+255", "flag":"🇹🇿", "name":"'. $lang['Tanzania'] .'"},
    {"code":"th", "calling_code":"+66", "flag":"🇹🇭", "name":"'. $lang['Thailand'] .'"},
    {"code":"tl", "calling_code":"+670", "flag":"🇹🇱", "name":"'. $lang['TimorLeste'] .'"},
    {"code":"tg", "calling_code":"+228", "flag":"🇹🇬", "name":"'. $lang['Togo'] .'"},
    {"code":"to", "calling_code":"+676", "flag":"🇹🇴", "name":"'. $lang['Tonga'] .'"},
    {"code":"tt", "calling_code":"+1868", "flag":"🇹🇹", "name":"'. $lang['TrinidadTobago'] .'"},
    {"code":"tn", "calling_code":"+216", "flag":"🇹🇳", "name":"' . $lang['Tunisia'] . '"},
    {"code":"tr", "calling_code":"+90", "flag":"🇹🇷", "name":"'. $lang['Turkey'] .'"},
    {"code":"tm", "calling_code":"+993", "flag":"🇹🇲", "name":"'. $lang['Turkmenistan'] .'"},
    {"code":"tv", "calling_code":"+688", "flag":"🇹🇻", "name":"'. $lang['Tuvalu'] .'"},
    {"code":"ug", "calling_code":"+256", "flag":"🇺🇬", "name":"'. $lang['Uganda'] .'"},
    {"code":"ua", "calling_code":"+380", "flag":"🇺🇦", "name":"'. $lang['Ukraine'] .'"},
    {"code":"ae", "calling_code":"+971", "flag":"🇦🇪", "name":"' . $lang['UAE'] . '"},
    {"code":"gb", "calling_code":"+44", "flag":"🇬🇧", "name":"'. $lang['UK'] .'"},
    {"code":"us", "calling_code":"+1", "flag":"🇺🇸", "name":"'. $lang['USA'] .'"},
    {"code":"uy", "calling_code":"+598", "flag":"🇺🇾", "name":"'. $lang['Uruguay'] .'"},
    {"code":"uz", "calling_code":"+998", "flag":"🇺🇿", "name":"'. $lang['Uzbekistan'] .'"},
    {"code":"vu", "calling_code":"+678", "flag":"🇻🇺", "name":"'. $lang['Vanuatu'] .'"},
    {"code":"ve", "calling_code":"+58", "flag":"🇻🇪", "name":"'. $lang['Venezuela'] .'"},
    {"code":"vn", "calling_code":"+84", "flag":"🇻🇳", "name":"'. $lang['Vietnam'] .'"},
    {"code":"ye", "calling_code":"+212", "flag":"🇪🇭", "name":"'. $lang['WesternSahara'] .'"},
    {"code":"ye", "calling_code":"+967", "flag":"🇾🇪", "name":"' . $lang['Yemen'] . '"},
    {"code":"zm", "calling_code":"+260", "flag":"🇿🇲", "name":"'. $lang['Zambia'] .'"},
    {"code":"zw", "calling_code":"+263", "flag":"🇿🇼", "name":"'. $lang['Zimbabwe'] .'"}
    ]');
}